#!/bin/sh

## 
## This script will auto-generate the AUTHORS attribution file.
## If your name does not display correctly, then please
## update the .mailmap file in the root repo directory
##

git log --reverse --format='%aN <%aE>' | perl -we '
BEGIN {
  %seen = (), @authors = ();
}
## Start
push @authors, "Bryant E. McDonnell <bemcdonnell\@gmail.com>\n";
while (<>) {
  next if $seen{$_};
  next if /Pena-Castellanos/; 
  next if /unknown/; 
  next if /Bryant/;
  next if /tryby.michael\@epa.gov/;
  $seen{$_} = push @authors, $_;
}

END {
  print "# Authors ordered by first contribution.\n";
  print "# Generated by tools/update-authors.sh\n";
  print "\n", @authors;
  print "\n\nAuthors with Contributions in the Public Domain:";
  print "\nMichael Tryby <tryby.michael\@epa.gov>";  
}
' > ../AUTHORS