name: Build Wheels

on: [push, pull_request]

jobs:
  build_wheels:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-14, ubuntu-latest]
        py: ["3.12", "3.13", "3.14"]

    name: Build & test on ${{ matrix.os }} / Python ${{ matrix.py }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@bec219d24cd3e171d82865faccec33120bb574f4 # v10.1.0
        with:
          python-version: ${{ matrix.py }}

      - name: Unit Test
        shell: bash
        run: uv run pytest

  publish:
    name: Publish Python 🐍 distribution 📦 to PyPI
    # only publish to PyPI on tag pushes
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/pyswmm
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@bec219d24cd3e171d82865faccec33120bb574f4 # v10.1.0

      - name: Build distributions
        run: uv build
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        if: github.ref_type == 'tag'
        with:
          generate_release_notes: true
          files: |
            dist/*.whl
            dist/*.tar.gz

      
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1